databases:
  - name: realtime_19f0
    databaseName: penny_postgresql_wise
    user: realtime_19f0_user

services:
  - type: web
    name: Realtime-search
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realtime_19f0
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false